FROM ansibleplaybookbundle/apb-base:canary

LABEL "com.redhat.apb.spec"=\
"LS0tCnZlcnNpb246IDEuMApuYW1lOiBhdXRvbWF0aW9uLWJyb2tlci1hcGIKZGVzY3JpcHRpb246\
IGRlcGxveXMgYXV0b21hdGlvbiBicm9rZXIgZm9yIHRoZSBzZXJ2aWNlLWNhdGFsb2cKYmluZGFi\
bGU6ICJGYWxzZSIKYXN5bmM6IG9wdGlvbmFsCm1ldGFkYXRhOgogIGRpc3BsYXlOYW1lOiBBdXRv\
bWF0aW9uIEJyb2tlciAoQVBCKQogIGxvbmdEZXNjcmlwdGlvbjoKICAgIEFuIEFQQiBmb3IgbWFu\
YWdpbmcgdGhlIGF1dG9tYXRpb24gYnJva2VyIGluIGEgY2x1c3RlcgogIGRlcGVuZGVuY2llczog\
W10KICBwcm92aWRlckRpc3BsYXlOYW1lOiAiUmVkIEhhdCwgSW5jLiIKcGxhbnM6CiAgLSBuYW1l\
OiBtYWluCiAgICBkZXNjcmlwdGlvbjogTWFuYWdlIHRoZSBhdXRvbWF0aW9uIGJyb2tlciBpbiBh\
IGNsdXN0ZXIKICAgIGZyZWU6ICJUcnVlIgogICAgbWV0YWRhdGE6CiAgICAgIGRpc3BsYXlOYW1l\
OiBEZWZhdWx0CiAgICAgIGxvbmdEZXNjcmlwdGlvbjoKICAgICAgICBUaGlzIHBsYW4gZGVwbG95\
cyB0aGUgYXV0b21hdGlvbiBicm9rZXIKICAgICAgY29zdDogJDAuMDAKICAgIHBhcmFtZXRlcnM6\
CiAgICAgIC0gbmFtZTogYnJva2VyX25hbWUKICAgICAgICB0aXRsZTogTmFtZSBvZiB0aGUgYnJv\
a2VyCiAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgZGVmYXVsdDogYXV0b21hdGlvbi1icm9r\
ZXIKICAgICAgLSBuYW1lOiBicm9rZXJfbmFtZXNwYWNlCiAgICAgICAgdGl0bGU6IE5hbWVzcGFj\
ZSBvZiB0aGUgYnJva2VyCiAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgZGVmYXVsdDogYXV0\
b21hdGlvbi1icm9rZXIKICAgICAgLSBuYW1lOiBicm9rZXJfaW1hZ2UKICAgICAgICB0aXRsZTog\
Q29udGFpbmVyIGltYWdlIGZvciB0aGUgYnJva2VyCiAgICAgICAgdHlwZTogc3RyaW5nCiAgICAg\
ICAgZGVmYXVsdDogYW5zaWJsZXBsYXlib29rYnVuZGxlL29yaWdpbi1hbnNpYmxlLXNlcnZpY2Ut\
YnJva2VyOmxhdGVzdAo="

# Add our role into the ansible roles dir
ADD playbooks /opt/apb/actions
ADD . /opt/ansible/roles/automation-broker-apb

RUN yum -y install epel-release openssl && yum clean all

RUN chmod -R g=u /opt/{ansible,apb}

USER apb
