FROM ansibleapp/ansibleapp-base
# MAINTAINER {{ $MAINTAINER }}

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"aWQ6IDg5ZGFiNTZkLWE3MTItNDcyNS1hMDY1LWRjYjZjOGUxZGU4OApuYW1lOiBhbnNpYmxlLXNl\
cnZpY2UtYnJva2VyLWFwYgppbWFnZTogYW5zaWJsZXBsYXlib29rYnVuZGxlL2Fuc2libGUtc2Vy\
dmljZS1icm9rZXItYXBiCmRlc2NyaXB0aW9uOiBBUEIgT3BlblNlcnZpY2VCcm9rZXIgaW1wbGVt\
ZW50YXRpb24KYmluZGFibGU6IGZhbHNlCmFzeW5jOiAidW5zdXBwb3J0ZWQiCnBhcmFtZXRlcnM6\
CiAgLSBuYW1lOiBkb2NrZXJodWJfdXNlcgogICAgZGVzY3JpcHRpb246IERvY2tlckh1YiBVc2Vy\
CiAgICB0eXBlOiBzdHJpbmcKICAtIG5hbWU6IGRvY2tlcmh1Yl9wYXNzCiAgICBkZXNjcmlwdGlv\
bjogRG9ja2VySHViIFBhc3MKICAgIHR5cGU6IHN0cmluZwogIC0gbmFtZTogb3BlbnNoaWZ0X3Rh\
cmdldAogICAgZGVzY3JpcHRpb246IE9wZW5zaGlmdCBUYXJnZXQKICAgIHR5cGU6IHN0cmluZwog\
IC0gbmFtZTogb3BlbnNoaWZ0X3VzZXIKICAgIGRlc2NyaXB0aW9uOiBPcGVuc2hpZnQgVXNlcgog\
ICAgdHlwZTogc3RyaW5nCiAgLSBuYW1lOiBvcGVuc2hpZnRfcGFzcwogICAgZGVzY3JpcHRpb246\
IE9wZW5zaGlmdCBQYXNzCiAgICB0eXBlOiBzdHJpbmcK"
ADD ansible /opt/ansible
ADD ansibleapp /opt/ansibleapp

RUN useradd -u 1001 -r -g 0 -M -b /opt/ansibleapp -s /sbin/nologin -c "ansibleapp user" ansibleapp
RUN chown -R 1001:0 /opt/{ansible,ansibleapp}
USER 1001
