apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: mediawiki123
spec:
  clusterServiceClassExternalName: dh-mediawiki-apb
  clusterServicePlanExternalName: default
  parameters:
    mediawiki_db_schema: "mediawiki"
    mediawiki_site_name: "Mediawiki-CI"
    mediawiki_site_lang: "en"
    mediawiki_admin_user: "ci-user"
    mediawiki_admin_pass: "admin"
