package version

// Version contains the broker version.
// DO NOT EDIT GENERATED FILE.
// This file is generated by a tito tag
// using templates/version.go.tmpl.
var Version = "1.0.4"
var MinAPBVersion = "1.0"
var MaxAPBVersion = "1.0"

