---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ broker_name }}-auth
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "delete"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  - apiGroups: ["networking.k8s.io", ""]
    # attributeRestrictions: null
    resources: ["networkpolicies"]
    verbs: ["create", "delete", "list"]
  - apiGroups: ["automationbroker.io"]
    # attributeRestrictions: null
    resources: ["bundles", "bundlebindings", "bundleinstances"]
    verbs: ["*"]
{% if 'authorization.openshift.io' in lookup('k8s', cluster_info='api_groups') %}
  - apiGroups: ["authorization.openshift.io"]
    resources: ["subjectrulesreview"]
    verbs: ["create"]
{% endif %}
{% if 'image.openshift.io' in lookup('k8s', cluster_info='api_groups') %}
  - apiGroups: ["image.openshift.io", ""]
    # attributeRestrictions: null
    resources: ["images"]
    verbs: ["get", "list"]
{% endif %}
{% if 'network.openshift.io' in lookup('k8s', cluster_info='api_groups') %}
  - apiGroups: ["network.openshift.io", ""]
    # attributeRestrictions: null
    resources: ["clusternetworks", "netnamespaces"]
    verbs: ["get"]
  - apiGroups: ["network.openshift.io", ""]
    # attributeRestrictions: null
    resources: ["netnamespaces"]
    verbs: ["update"]
{% endif %}
