---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: asb-user-access
  labels:
{% if broker_sandbox_role == 'admin' %}
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
{% endif %}
{%if broker_sandbox_role == 'edit' %}
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
{% endif %}
rules:
- apiGroups: ["automationbroker.io"]
  resources: ["access"]
  verbs: ["create"]
